# name: 0x96f
# variant: dark
selection_foreground    #fcfcfc
selection_background    #514f52

background              #262427
foreground              #fcfcfc

color0                 #262427
color1                 #ff7272
color2                 #bcdf59
color3                 #ffca58
color4                 #49cae4
color5                 #a093e2
color6                 #aee8f4
color7                 #fcfcfc
color8                 #676567
color9                 #ff7272
color10                #bcdf59
color11                #ffca58
color12                #49cae4
color13                #a093e2
color14                #aee8f4
color15                #fcfcfc

cursor                  #fcfcfc
cursor_text_color       #262427

url_color               #49cae4

active_tab_foreground  #fcfcfc
active_tab_background  #ffca58
inactive_tab_foreground #fcfcfc
inactive_tab_background #3b393c
