kitty_mod ctrl+shift
clear_all_shortcuts yes
map kitty_mod+r load_config_file
map kitty_mod+c copy_to_clipboard 
map kitty_mod+v paste_from_clipboard 
# Navegation
# map kitty_mod+h neighboring_window left
# map kitty_mod+j neighboring_window down
# map kitty_mod+k neighboring_window up
# map kitty_mod+l neighboring_window right
# map kitty_mod+shift+h previous_tab
# map kitty_mod+tab next_tab
# map kitty_mod+shift+l next_tab
# map kitty_mod+shift+tab previous_tab
# map kitty_mod+shift+1 goto_tab 1
# map kitty_mod+shift+2 goto_tab 2
# map kitty_mod+shift+3 goto_tab 3
# map kitty_mod+shift+4 goto_tab 4
# map kitty_mod+shift+5 goto_tab 5
# map kitty_mod+t next_layout
# Move
# map kitty_mod+ctrl+h move_window left
# map kitty_mod+ctrl+j move_window down
# map kitty_mod+ctrl+k move_window up
# map kitty_mod+ctrl+l move_window right
# Launch
# map kitty_mod+n launch --location=vsplit
# map kitty_mod+d launch --location=hsplit
# map kitty_mod+q close_window
# map kitty_mod+shift+n new_tab
# map kitty_mod+shift+q close_tab

map kitty_mod++ change_font_size all +2.0
map kitty_mod+- change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
