
# Config
# -- Font
font_family IosevkaTerm Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 17.0
disable_ligatures never
# active_tab_font_style italic
# inactive_tab_font_style normal
# Others
cursor_shape beam
cursor_shape_unfocused underline
cursor #FD5CFF
cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 4
cursor_trail_color #C011C2
scrollback_lines 1000
scrollback always
scrollback_pager nvim #
allow_remote_control yes
listen_on unix:/tmp/mykitty
# -- keymaps
map ctrl+alt+r load_config_file
map page_up scroll_page_up
map page_down scroll_page_down
map alt+s show_scrollback
