# BEGIN_KITTY_THEME
# noirbuddy-oxide
include Color-scheme.conf
include Fonts.conf
include Text-cursor-customization.conf
include Scrollback.conf
include Mouse.conf
include Performance-tuning.conf
include Terminal-bell.conf
include Window-layout.conf
include Tab-bar.conf
include Advanced.conf
include OS-specific-tweaks.conf
include Keyboard-shortcuts.conf
# END_KITTY_THEME
