[opener]
edit = [
    { run = 'nvim \"$@\"', block = true, for = "unix" }
]
pdf = [
  { run = 'okular \"$@\"', orphan = true, for = "unix" }
]
image = [
    { run = 'gthumb \"$@\"', orphan = true, for = "unix"}
]
notebook = [
    { run = 'code \"$@\"', orphan = true, for = "unix"}
]
office = [
    { run = 'libreoffice \"$@\"', orphan = true, for "unix"}
]
open = [
  { run = 'handlr open \"$@\"', desc = "Abrir con app por defecto" }
]
