[mgr]
ratio = [ 1, 3, 4]
sort_by = "natural"
# sort_reverse = true
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
scrolloff = 200

[preview]
max_width = 1000
max_height = 1800
image_filter = "lanczos3"
image_quality = 90


[opener]
edit = [
    { run = 'nvim %s', block = true, for = "unix" }
]
pdf = [
  { run = 'okular %s', orphan = true, for = "unix" }
]
image = [
    { run = 'gthumb %s', orphan = true, for = "unix"}
]
notebook = [
    { run = 'code %s', orphan = true, for = "unix"}
]
office = [
    { run = 'libreoffice %s', orphan = true, for = "unix"}
]
# open = [
#   { run = 'xdg-open %s1', desc = "Abrir con app por defecto" }
# ]

# [open]
# rules = [
#   { name = "*.pdf", use = "pdf" },
#   { name = "*.docx", use = "office" },
#   { name = "*.xlsx", use = "office" },
#   { name = "*.pptx", use = "office" },
#   { name = "*.png", use = "open" },
#   { name = "*.jpg", use = "open" },
#   { name = "*.mp4", use = "open" },
#   { name = "*.ipynb", use = "notebook" },
#   { name = "*.txt", use = "edit" },
#   { name = "*.c", use = "edit" },
#   { name = "*.py", use = "edit" },
#   { name = "*.md", use = "edit" }
# ]
#
