preload = /home/carlosm/Pictures/Wallpapers/berserker-light.png
preload = /home/carlosm/Pictures/Wallpapers/jinx-arcane-sit-dark.jpg
wallpaper = ,/home/carlosm/Pictures/Wallpapers/jinx-arcane-sit-dark.jpg
# wallpaper {
# 	monitor = eDP-1
# 	path = ~/Pictures/Wallpapers/jinx-arcane-sit-dark.jpg
# 	fit_mode = cover
# }
# wallpaper {
# 	monitor = HDMI-A-1
# 	path = ~/Pictures/Wallpapers/jinx-arcane-sit-dark.jpg
# 	fit_mode = cover
# }
