# Apps
$terminal = foot
$browser = zen-browser
$fileExplorer = nautilus
$pdfViewer = okular
# $editor = code
$menu = rofi -show drun -theme ~/.config/rofi/layouts/list-apps.rasi
# $menu = rofi -show drun -theme-str '#prompt { text: "Apps"; }' -theme ~/.config/rofi/layouts/list-apps.rasi
# $menu = rofi -show drun -p "Apps" 

# Touchpad
$touchpadFingers = 3
$touchpadFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurSize = 8
$blurPasses = 2
$blurXray = 0

# Shadow
$shadowEnabled = false
$shadowRange = 10
$shadowRenderPower = 10
$shadowColor = rgba($shadow7F)
$shadowInactiveColor = rgba($surfaceContainerLowest7F)

# Window styling
$windowActiveOpacity = 0.98
$windowInactiveOpacity = 0.95
$windowRounding = 10
$windowRoundingPower = 4
$windowBorderSize = 5
$activeWindowBorderColour = rgba($primaryFF)
$inactiveWindowBorderColour = rgba($outlineVariantFF)
                #top, right, bottom, left
$windowGapsIn =  5,  5,     5,     5
$windowGapsOut = 10,  10,     10,     10

# Misc
$volumeStep = 5  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 12

# -------- Keybinds -----------------------------------

# Workspaces
$kbMoveWinToWs = Super+Shift
$kbGoToWs = Super
$kbToggleSpecialWs = Super, S

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
# $kbWindowPip = Super+Alt, Backslash
# $kbPinWindow = Super, P
# $kbWindowFullscreen = Super, F
# $kbWindowBorderedFullscreen = Super+Alt, F
# $kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Special workspace toggles
# $kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
# $kbTerminal = Super, N
# $kbBrowser = Super, B
# $kbEditor = Super, C
# $kbFileExplorer = Super, E

# Misc
# $kbSession = Ctrl+Alt, Delete
# $kbClearNotifs = Ctrl+Alt, C
# $kbShowPanels = Super, K
# $kbLock = Ctrl+Super, L
# $kbRestoreLock = Super+Alt, L


