# Apps
$terminal = foot
$browser = zen-browser
$fileExplorer = nautilus
$pdfViewer = okular
# $editor = code
$menu = rofi -show drun -theme ~/.config/rofi/layouts/list-apps.rasi
# $menu = rofi -show drun -theme-str '#prompt { text: "Apps"; }' -theme ~/.config/rofi/layouts/list-apps.rasi
# $menu = rofi -show drun -p "Apps" 

# Touchpad
$touchpadFingers = 3
$touchpadFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurSize = 8
$blurPasses = 2
$blurXray = 0

# Shadow
$shadowEnabled = false
$shadowRange = 10
$shadowRenderPower = 10
$shadowColor = rgba($base007F)
$shadowInactiveColor = rgba($base017F)

# Window styling
$windowActiveOpacity = 0.98
$windowInactiveOpacity = 0.95
$windowRounding = 10
$windowRoundingPower = 4
$windowBorderSize = 5
$activeWindowBorderColour = rgba($base0DFF)
$inactiveWindowBorderColour = rgba($base027F)
                #top, right, bottom, left
$windowGapsIn =  5,  5,     5,     5
$windowGapsOut = 5,  5,     5,     5

# Misc
$volumeStep = 5  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 12

# -------- Keybinds -----------------------------------

# Workspaces
$kbMoveWinToWs = Super+Shift
$kbGoToWs = Super
$kbToggleSpecialWs = Super, S

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbCloseWindow = Super, Q

$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

