decoration {
    rounding = $windowRounding
    rounding_power = $windowRoundingPower

    # Change transparency of focused and unfocused windows
    active_opacity = $windowActiveOpacity
    inactive_opacity = $windowInactiveOpacity

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        # ignore_window = false
        color = $shadowColor
        color_inactive = $shadowInactiveColor
        # offset = -1 1
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = $blurEnabled
        size = $blurSize
        special = $blurSpecialWs
        passes = $blurPasses
        new_optimizations = true
        ignore_opacity = true
        xray = $blurXray
        # input_methods = $
        # vibrancy = 0.1696
    }
}

