# exec-once = waybar
exec-once = qs
exec-once = /usr/bin/awww-daemon
exec-once = kitty --listen-on unix:/tmp/kitty.sock --single-instance
exec-once = wl-paste --watch cliphist store

# Cursors
# exec-once = hyprctl setcursor $cursorTheme $cursorSize
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
# exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

exec = /home/carlosm/.config/scripts/system/refresh-display.sh
