gesture = 3, horizontal, workspace
# gesture = 3, down, mod: SUPER, scale: 1.0, fullscreen
gesture = 3, up, scale: 1.0, fullscreen
gesture = 3, down, dispatcher, exec, /usr/bin/makoctl dismiss -a
# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

